defaults:
  - _self_
  - base_train
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 

img_list_path: data/imagenet_files_bluestone.txt
subset_size: 10000
batch_size: 64
n_epochs: 20
log_every: 10
save_every: 2
server_port: "29500"
